default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: thoughts_on_rails_development

test:
  <<: *default
  database: thoughts_on_rails_test

production:
  primary: &primary_production
    <<: *default
    database: thoughts_on_rails_production
    username: thoughts_on_rails
    password: <%= ENV["THOUGHTS_ON_RAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: thoughts_on_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: thoughts_on_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: thoughts_on_rails_production_cable
    migrations_paths: db/cable_migrate
